export const JWT_AUTH_KEY = 'JWT_AUTH_KEY';

export const MAILGUN_API_KEY = 'MAILGUN_API_KEY';
export const MAILGUN_DOMAIN = 'MAILGUN_DOMAIN';
export const MAILGUN_SENDER = 'MAILGUN_SENDER';

export const LANDING_URL = 'LANDING_URL';
